### ISSUE TITLE
角色图片超出界限的问题

### ISSUE THREAD

**Issue by xuexue49** [shkongzhu/YoWhite#2]
将public/template/clan/panel.html35和42行改一下,稍微缩小一下就不会出现挡住的问题了
div class="character" style="height: 165px; position: relative;z-index: 99;width:88%;transform:translateX(6%);"
el-row style="margin-bottom: 5px;width:88%;transform:translateX(6%)"
![image](https://user-images.githubusercontent.com/65126770/88213955-fc155b80-cc8b-11ea-975e-e0676ab0dd0a.png)

**Comment by xuexue49** [comment]
<div class="character" style="height: 165px; position: relative;z-index: 99;width:88%;transform:translateX(6%);">
<el-row style="margin-bottom: 5px;width:88%;transform:translateX(6%)">

**Comment by ishkong** [comment]
已修复 感谢
