### ISSUE TITLE
给会战页面加了一点自适应,在离谱的全面屏手机里面看起来好了一点

### ISSUE THREAD

**Issue by xuexue49** [shkongzhu/YoWhite#3]
@media (max-width: 480px){html{zoom:0.8;}}
  @media (max-width: 360px){html{zoom:0.75;}}
加在panel.html的styel里面
![CC UF~6P CVCMP}_V6H50I8](https://user-images.githubusercontent.com/65126770/88329321-5382fc80-cd5c-11ea-9128-66c12f3ab6da.jpg)

**Comment by ishkong** [comment]
已添加，感谢建议
