### ISSUE TITLE
查刀界面的表格希望能做一个缩放，现在一页显示不全需要左右滑动有点难受

### ISSUE THREAD

**Issue by quicksilver2000** [shkongzhu/YoWhite#4]
![image](https://user-images.githubusercontent.com/53461359/88450436-7bb84b80-ce81-11ea-8b19-bad2626b4281.png)
如图
赞美大佬做的UI
希望大佬优化一下，多谢了
成员列表同

**Comment by ishkong** [comment]
已尝试优化，请获取最新文件
